version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "vitest"
  ]

[[analyzers]]
name = "secrets"

[[transformers]]
name = "prettier"